import { openAiLLM } from "../../../config/llm.ts";
import type { AgentState } from "../../state/state.ts";
import z from "zod";

export async function confirmChanges(state: AgentState) {
  const { profile, messages, needsConfirmation } = state;

  if (!profile) {
    console.error("❌ No profile in state!");
    return { isComplete: false };
  }

  // If we already showed the summary and are waiting for confirmation
  if (needsConfirmation) {
    const lastMessage = messages[messages.length - 1];
    console.log("📨 User responded to confirmation:", lastMessage);

    const interpretLLM = openAiLLM.withStructuredOutput(
      z.object({
        isConfirming: z.boolean(),
        correction: z.string().optional(),
      })
    );

    const interpretation = await interpretLLM.invoke([
      {
        role: "system",
        content: `You are NerdyResume by @nerdyabhi - interpret if user is confirming or wants corrections.

Examples of confirming: "yes", "looks good", "correct", "perfect", "yep", "ok", "yeah", "ye", "confirm"
Examples of correcting: "change email to...", "actually I worked at...", "no, my name is...", "fix phone"

Set isConfirming = true if they're confirming.
Set isConfirming = false if they want changes.`,
      },
      {
        role: "user",
        content: `User said: "${lastMessage}"`,
      },
    ]);

    console.log("🔍 Interpretation:", interpretation);

    if (!interpretation.isConfirming) {
      console.log("✏️ User wants to correct something");
      return {
        isComplete: false,
        profile: undefined,
        needsConfirmation: false, // Reset
      };
    }

    console.log("✅ User confirmed - profile is complete");
    return {
      isComplete: true,
      needsConfirmation: false, // Reset
    };
  }

  // First time - generate summary
  console.log("📋 Generating confirmation summary");

  const summaryResponse = await openAiLLM.invoke([
    {
      role: "system",
      content: `You are NerdyResume - an AI resume assistant created by @nerdyabhi (https://github.com/nerdyabhi) 🤖

Create a clear, professional summary of the user's profile for confirmation.

Use markdown formatting and emojis. Make it easy to read and well-organized.

STRUCTURE:
# 📋 Your Profile Summary

**Name:** [name]
**Email:** [email]
**Phone:** [phone]

## 💼 Work Experience
[format nicely with bullet points, include company, role, duration]

## 🎓 Education
[if present - degree, university, dates, CGPA]

## 🏆 Achievements
[if present]

## 💻 Technical Skills
[list in categories if possible]

## 🔗 Profile Links
[if present - GitHub, LinkedIn, LeetCode, etc]

---
*Generated by NerdyResume 🤖 | Created by @nerdyabhi*

Does this look correct? Reply 'yes' to save, or tell me what needs to be corrected.`,
    },
    {
      role: "user",
      content: JSON.stringify(profile, null, 2),
    },
  ]);

  const summary = summaryResponse.content as string;

  return {
    confirmationSummary: summary,
    needsConfirmation: true, // Set flag - we need user input
    isComplete: false, // Not complete yet!
  };
}